---
  test_name: Create a user

  stages:
    - name: create a user
      request:
        url: http://localhost:5000/user
        json:
          user_name: fg112111
          hashed_password: fg112111
          full_name: fg112111
          email_id: fg112111
        method: POST
        headers:
          content-type: application/json
      response:
        status_code: 201

---
  test_name: update a user's hashed_password

  stages:
    - name: update a user hashed_password
      request:
          url: http://localhost:5000/user
          json:
            hashed_password: bhingre
          method: PATCH
          auth:
              - parag
              - bhingre

          headers:
            content-type: application/json
      response:
          status_code: 201

---
test_name: Delete existing user

stages:
  - name: Make sure you delete existing user
    request:
      url: http://localhost:5000/user
      auth:
        - parag
        - bhingre

      method: DELETE
      headers:
        content-type: application/json
    response:
      status_code: 200
